[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = [
    "E501",
    "E203",
    "W503", 
    "E501",
    "W291",
]